;;;		Maiko Garbage Collector Tests
;; Start a clean Maiko Full.Sysout.
;; Open an Interlisp EXEC.
LOAD(GCHAX.LCOM)
LOAD({ERIS}<TEST>GC>HAND>MAIKO-GC-TESTS.LCOM)
(STORAGE)
;; note the counts for types starting with SEDIT::.
DV DIRECTORIES
DV DISPLAYFONTDIRECTORIES
DV INTERPRESSFONTDIRECTORIES
;; close the SEdit windows
(FRPTQ 100 (RECLAIM))
(STORAGE)
;; make sure that all the SEDIT:: types got reclaimed.
SHH(MAIN-GC-TEST 5)  ; or any number
;; look at the dribble to make sure that things get
;; reclaimed.  Specifically, look at:
;;	FLOATPs
;;	FIXPs
;;	BIGNUMs
;;	STREAMs
;;	PIECEs
;;	TEXTOBJs
;;	VMEMPAGEPs
;;	COMPILED-CLOSUREs
;; The final 2 things MAIN-GC-TEST does are to exhaust atom
;; space artificially (and restore it to its pre-existing state),
;; and exhaust storage for real.  Both of these should cause errors
;; from which you can ^ to continue the test.
