(setq *compile-verbose* nil)
(setq *load-verbose* nil)
#+(or) (pushnew "/home/edi/parker/" mk:*central-registry*)
#+(or) (mk:load-system "regex2" :compile-during-load t)
(mk:compile-system "cl-ppcre-test")
(load "testdata.lisp")
(dribble "results")
#+(or) (cl-ppcre-test::time-all-parker)
(cl-ppcre-test:test)
(quit)
