#! /bin/csh -f
#
#	automatic loadup procedure
#	run 2nd and 3rd step for loadup
#
set LDE			= $HOME/maiko/sunos4.sparc/lde
set LDEPATH		= $HOME/maiko/sunos4.sparc
set INITLDE		= $HOME/maiko/sunos4.sparc/ldeinit
set INITLDEPATH		= $HOME/maiko/init.sparc
set FULL_SYSOUT		= /python1/fuji/sysouts/FULL.SYSOUT
set FIRST_REM_CM	= $HOME/SUNLOADUP/XREM.CM
set SECOND_REM_CM	= $HOME/SUNLOADUP/LOADUP-REM.CM
#

#first create INIT.SYSOUT and INIT.DLINIT

# Boot INIT.DLINIT and LOGOUT.
set path=($INITLDEPATH /bin /usr/bin /usr/ucb /etc /usr/etc)
unsetenv LDEDESTSYSOUT
cp $FIRST_REM_CM ~/REM.CM
# save your lisp.virtualmem
if( -e ~/lisp.virtualmem ) then
	mv ~/lisp.virtualmem ~/lisp.virtualmem.save
endif
$INITLDE ~/INIT.DLINIT -INIT 

# Finally boot ~/lisp.virtualmem created by previous LOGOUT,
# and MAKESYS LISP.SYSOUT
set path=($LDEPATH /bin /usr/bin /usr/ucb /etc /usr/etc)
cp $SECOND_REM_CM ~/REM.CM
$LDE ~/lisp.virtualmem
