#! /bin/csh -f
#
#	automatic loadup procedure thru to FULL.SYSOUT
#
#set LDE			= $HOME/maiko/sunos4.sparc/lde
set LDE			= $HOME/maiko/irix.sgi/lde
set LDE2		= $HOME/maiko/irix.sgi/lde
set LDEPATH		= $HOME/maiko/irix.sgi
set INITLDE		= $HOME/maiko/irix.sgi/ldeinit
set INITLDEPATH		= $HOME/maiko/init.sgi
#set FULL_SYSOUT		= /usr/local/sysouts/FULL.SYSOUT
set FULL_SYSOUT = $HOME/bigLISP.SYSOUT
#set FULL_SYSOUT = $HOME/bigLISP.SYSOUT
set FIRST_REM_CM	= $HOME/SUNLOADUP/XREM.CM
set SECOND_REM_CM	= $HOME/SUNLOADUP/LOADFULL-REM.CM
#

#first create INIT.SYSOUT and INIT.DLINIT
set path=($LDEPATH /bin /usr/bin /usr/ucb /etc /usr/etc)
setenv	LDEINIT	$HOME/SUNLOADUP/INIT.MAKECLTL2SGI
rm ~/REM.CM
$LDE $FULL_SYSOUT


# Boot INIT.DLINIT and LOGOUT.
set path=($INITLDEPATH /bin /usr/bin /usr/ucb /etc /usr/etc)
unsetenv LDEDESTSYSOUT
cp $FIRST_REM_CM ~/REM.CM
# save your lisp.virtualmem
if( -e ~/lisp.virtualmem ) then
	mv ~/lisp.virtualmem ~/lisp.virtualmem.save
endif
$INITLDE ~/INIT.DLINIT -INIT 

# Finally boot ~/lisp.virtualmem created by previous LOGOUT,
# and MAKESYS LISP.SYSOUT
#set path=(~ /bin /usr/bin /usr/ucb /etc /usr/etc)
set path=( $LDEPATH /bin /usr/bin /usr/ucb /etc /usr/etc )
cp $SECOND_REM_CM ~/REM.CM
$LDE2 ~/lisp.virtualmem


