#! /bin/csh -f
#
#	automatic loadup procedure
#	Remove D-Machine specific code version
#
set LDE			= $HOME/maiko/sunos4.sparc/lde
set LDEPATH		= $HOME/maiko/sunos4.sparc
set INITLDE		= $HOME/maiko/init.sparc/lde
set INITLDEPATH		= $HOME/maiko/init.sparc
set FULL_SYSOUT		= /usr/local/sysouts/FULL.SYSOUT
set FIRST_REM_CM	= $HOME/SUNLOADUP/XREM.CM
set SECOND_REM_CM	= $HOME/SUNLOADUP/LOADUP-NODMACHINE-REM.CM
#

#first create INIT.SYSOUT and INIT.DLINIT
set path=($LDEPATH /bin /usr/bin /usr/ucb /etc /usr/etc)
setenv	LDEINIT	$HOME/SUNLOADUP/INIT.MAKEINIT
rm ~/REM.CM
$LDE $FULL_SYSOUT

# Boot INIT.DLINIT and LOGOUT.
set path=($INITLDEPATH /bin /usr/bin /usr/ucb /etc /usr/etc)
unsetenv LDEDESTSYSOUT
cp $FIRST_REM_CM ~/REM.CM
# save your lisp.virtualmem
if( -e ~/lisp.virtualmem ) then
	mv ~/lisp.virtualmem ~/lisp.virtualmem.save
endif
$INITLDE ~/INIT.DLINIT -INIT 

# Finally boot ~/lisp.virtualmem created by previous LOGOUT,
# and MAKESYS LISP.SYSOUT
set path=($LDEPATH /bin /usr/bin /usr/ucb /etc /usr/etc)
cp $SECOND_REM_CM ~/REM.CM
$LDE ~/lisp.virtualmem
