;;; auto-generated from file #p"generate.lisp"
(IN-PACKAGE :CL-USER)
(LOAD #p"defpackage.lisp")
(COMPILE-FILE #p"files/arrays.olisp")
(COMPILE-FILE #p"files/bignum.olisp")
(COMPILE-FILE #p"files/boehm-gc.olisp")
(COMPILE-FILE #p"files/clos.olisp")
(COMPILE-FILE #p"files/crc40.olisp")
(COMPILE-FILE #p"files/deflate.olisp")
(COMPILE-FILE #p"files/gabriel.olisp")
(COMPILE-FILE #p"files/hash.olisp")
(COMPILE-FILE #p"files/math.olisp")
(COMPILE-FILE #p"files/ratios.olisp")
(COMPILE-FILE #p"files/richards.olisp")
(COMPILE-FILE #p"files/misc.olisp")
