name: Report an issue with the **Medley Interlisp for the Newcomer** primer
description: Use this template to report issues or make suggestions 
title: Title of your issue
assignees: ''
labels: primer, documentation
body:
  - type: dropdown
    id: problemType
    attributes:
      label: "What type of issue are you reporting?"
      options:
        - Suggested improvement
        - Incorrect explanation / code sample
        - Confusing explanation
        - Outdated information
        - Broken link
        - Typo / Grammar
      validations:
        required: true
  - type: dropdown
    id: location
    attributes:
      label: "Section of the primer where the issue occurs"
      options:
        - Introduction
        - Medley online and Medley Local
        - Understanding and Navigating the Interface
        - Understanding Lisp Syntax
        - Atoms, Functions and Lists
        - Variable Bindings and Scope
        - Iterators and Conditionals
        - The File Browser
        - Debugging
        - Editing functions with SEdit
        - Build Your First Interactive Program
        - Saving Your Work
        - TEdit, The WYSIWYG Editor
        - Drawing and Displaystreams
        - Making a Graph with Grapher
        - Additional Resources
        - General Feedback (not specific to a section)
      validations:
        required: true  
  - type: input
    id: issueLocationDetails
    attributes:
      label: "Please provide more details about the location of the issue"
      description: "For example, the specific page title, section heading, or code sample number."
    validations:
      required: false
  - type: textarea
    id: issueDescription
    attributes:
      label: "Description of the issue"
      description: "Please provide a detailed description of the issue you encountered."
    validations:
      required: true
  - type: textarea
    id: suggestedFix
    attributes:
      label: "Suggested fix or improvement"
      description: "If you have a suggestion for how to fix or improve the issue, please provide it here."
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Thank you for helping us improve the **Medley Interlisp for the Newcomer** primer!"