name: New "What People Are Saying" entry
description: 'Suggest a new entry for the "What People are Saying" page'
title: "What People Are Saying suggestion"
body:
  - type: dropdown
    id: contentType
    attributes:
      label: "What type of entry?"
      options:
        - Blog
        - Tweet
        - Email
        - Other
    validations:
      required: true
  - type: input
    id: entryLink
    attributes:
      label: Link to entry
      description: "What is the link to the item we should add to the **What People are Saying** page?"
    validations:
      required: true
  - type: textarea
    id: additionalInformation
    attributes:
      label:  Additional information
      description: "Use this space to supply any additional information on the suggested item."
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Thank you for your suggestion!"
