#!/bin/sh

pick=$0

case "$1" in

    "issue")			# pick issue: choose issue at random
	issue=`gh issue list -L 1000 -R interlisp/medley | shuf -n 1 |  sed 's/\([0-9]*\).*/\1/'`
	gh issue view $issue -R interlisp/medley -w
	gh issue view $issue -R interlisp/medley
	;;

      "oneof")			# pick oneof a b c: choose one 
	shift
	shuf -n 1 -e $@
	;;

    "dir")			# pick dir: choose a directory
	$pick oneof lispusers library sources doctools internal
	;;

    "project" )			# pick repo or subproject
        $pick oneof clos rooms notecards online test gitbook CLTL2 guidelines
	;;

    "file")			# pick file: choose a file in a directory
	                        # must be run from medleydir
	if [ -z $MEDLEYDIR ]; then
	    if [ -x run-medley ]; then
		MEDLEYDIR=`pwd`
	    elif [ -x medley/run-medley ]; then
		MEDLEYDIR=./medley
	    else
		echo "MEDLEYDIR not found"
	    fi
	fi	
	cd $MEDLEYDIR
	dir=$2
	if [ -z $dir ]; then
	    dir=`$pick dir`
	fi
	find ./$dir -type f | shuf -n 1
	;;
    "")
	$pick `$pick oneof file issue project`
	;;

    "*")			# something else
	echo "$1" not understood
	;;
esac

    
