#!/bin/bash

# Get the parameters
previous_head=$1
new_head=$2
is_branch_checkout=$3

# Print some info
echo "Checkout complete!"
# echo "Previous HEAD: $previous_head"
# echo "New HEAD: $new_head"
# echo "Branch checkout: $is_branch_checkout"

if [ "$is_branch_checkout" -eq 1 ]; then
    find . -name "*.~[1-9]*~" -exec ./scripts/find-orphaned-versions.sh {} \;
fi
