#*******************************************************************************
# buidReleaseInclDocker.yml
#
# Interlisp webflow to build a Medley release and push it to github.
# And to build a multiplatform Docker image for the release and push it to Docker Hub.
#
# This workflow just calls two reuseable workflows to the two task:
# buildLoadup.yml and buildDocker.yml
#
# 2022-01-18 Frank Halasz
#
# Copyright 2022 by Interlisp.org
#
# ******************************************************************************


name: "Build/Push Release & Docker"

# Run this workflow on ...
on:
  workflow_dispatch:
  

# Jobs that compose this workflow
jobs:
  # Build Loadup
  do_release:
    uses: ./.github/workflows/buildLoadup.yml
    
  # Build Docker Image
  do_docker:
    needs: do_release
    uses: ./.github/workflows/buildDocker.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
