#*******************************************************************************
# doHCFILES.yml
#
# Interlisp workflow to run HCFILES.  HCFILES prints out PDF files for all of the
# files in the Medley directory and posts them on interlisp.org.
#  
# This workflow is designed to run in the "src" repo - which is clone of the Medley
# repo in which the HCFILES are created.  HCFILES is done in a clone so as the
# generated PDF files don't "pollute" the working Medley repo.
#
# HCFILES pdf output is posted on interlisp.org via github pages on the src directory.
#
# This workflow is designed to be kickjed off by the buildReleaseInclDocker
# workflow running in the Medley repo, once the release has been completed successfully
#
# Copyright 2024 by Interlisp.org
#
# ******************************************************************************

name: Run HCFILES

# Run this workflow on ...
on:
  workflow_dispatch:
    inputs:
      draft:
        description: "Mark this as a draft release"
        type: choice
        options:
        - 'false'
        - 'true'
      force:
        description: "Force build even if build already successfully completed for this commit"
        type: choice
        options:
        - 'false'
        - 'true'

defaults:
  run:
    shell: bash

jobs:

  run_HCFILES:

    runs-on: ubuntu-latest

    steps:

      - name: Update src repo
        run: gh repo sync interlisp/src --branch master --source interlisp/medley
        env:
          GITHUB_TOKEN: ${{ secrets.ONLINE_TOKEN }}

      - name: Checkout updated src repo
        uses: actions/checkout@v4

      - name: Download Maiko
        run: |
          gh release download --output /tmp/maiko.tgz \
                              --repo ${{ github.repository_owner }}/maiko \
                              --pattern '*-linux.x86_64.tgz'
          tar -xzf /tmp/maiko.tgz"
        env:
          GITHUB_TOKEN: ${{ secrets.MAIKO_TOKEN }}

      - name: Install vnc
        run: sudo apt-get update && sudo apt-get install -y tightvncserver

      - name: Build full.sysout
        run: |
          Xvnc -geometry 1280x720 :0 &
          export DISPLAY=":0"
          scripts/loadup-full.sh

      - name: Create new branch


      - name: Run HCFILES
        run: |
          scripts/do_hcfiles.sh

      - name: Update gh-pages branch



