name: 'Test Docker Login'

# Run this workflow on ...
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    

jobs:

  login_test:
    runs-on: ubuntu-latest
    steps:
      - id: only_step
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


