#*******************************************************************************
# weeklyBuild.yml
#
# Interlisp webflow to schedule a weekly build of Medley, build a Docker image, push that
# image to DockerHub, kickoff an online Medley build with that Docker imnage and
# kickoff a fresh run of HCFILES.
#
# This workflow does no real work, it just calls buildReleaseInclDocker.yml with the default inputs
# (to make up for the fact that Github Actions does not have a mechanism for providing default inputs
# to a scheduled workflow)
#
# 2026-07-15 Frank Halasz
#
# Copyright 2026 by Interlisp.org
#
# ******************************************************************************


name: "Run Weekly Build"

# Run this workflow on ...
on:
  schedule:
    - cron: '17 9 * * 3'

  workflow_dispatch:

jobs:

  # Build Loadup
  do_build:
    uses: ./.github/workflows/buildReleaseInclDocker.yml
    with:
        maiko_release: "Latest"
        draft: false
        force: false
        online: true
    secrets: inherit

